source 'https://cdn.cocoapods.org/'
source 'git@github.com:PhenixRTS/CocoaPodsSpecs.git' # Phenix private repository

platform :ios, '13.0'
use_frameworks!
inhibit_all_warnings!

def phenix
  pod 'PhenixSdk', '~> 2020.0.0'
end

target 'PhenixGroups' do
  phenix
  pod 'SwiftLint', '~> 0.39.2'
end

target 'PhenixCore' do
  phenix
end

target 'PhenixCoreIntegrationTests' do
end

target 'PhenixCoreUnitTests' do
end
