source 'https://cdn.cocoapods.org/'
source 'git@github.com:PhenixRTS/CocoaPodsSpecs.git' # Phenix private repository

platform :ios, '13.0'
use_frameworks!
inhibit_all_warnings!

def phenix
  pod 'PhenixSdk', '2022.0.4'
  pod 'PhenixCore', :path => '../PhenixCore'
  pod 'PhenixDebug', :path => '../PhenixDebug'
  pod 'PhenixDeeplink', :path => '../PhenixDeeplink'
end

target 'PhenixGroups' do
  phenix
  pod 'SwiftLint', '~> 0.49.1'
end

target 'PhenixGroupsUnitTests' do

end
